/* BRICKLORIAN
   Created by Mariusz Aleksandrowicz via AI-driven workflows.
   Licensed under the MIT License. */
/* ================= i18n (English default, 36 languages) ================= */
const L10N = {
  en: { kicker:'WELCOME TO', tagline:'Classic falling-block mechanics reimagined. Pick your theme, clear lines, and watch them burst — before the bricks hit the ceiling.', pick:'— CHOOSE A STYLE —', d_classic:'80s arcade vibe — pure, simple retro.', d_neon:'Neon, chrome and the night city', d_rune:'Gold, runes and enchanted stones', d_space:'Star fields, gold and steel', lang:'LANGUAGE', bg:'BACKGROUND', st:'Static', an:'Animated', play:'PLAY', k_space:'Space', h_move:'move', h_rot:'rotate', h_soft:'drop', h_hard:'hard drop', h_pause:'pause', h_restart:'restart', h_menu:'menu', score:'SCORE', lines:'LINES', next:'NEXT', go1:'GAME OVER', go2:'Press R to play again', go3:'Press C to see credits', go4:'Press Esc to see the menu', cleared:'CLEARED!', double:'DOUBLE!', triple:'TRIPLE!' },
  pl: { kicker:'WITAJ W', tagline:'Kultowa mechanika spadających klocków w nowym wydaniu. Wybierz klimat, zapełniaj linie i obserwuj eksplozje — zanim sięgną sufitu.', pick:'— WYBIERZ STYL —', d_classic:'Klimat lat 80. — prosty, retro arcade', d_neon:'Neon, chrom i nocne ulice', d_rune:'Złoto, runy i magiczne kamienie', d_space:'Gwiezdne pole, złoto i stal', lang:'JĘZYK', bg:'TŁO', st:'Statyczne', an:'Animowane', play:'GRAJ', k_space:'Spacja', h_move:'ruch', h_rot:'obrót', h_soft:'spadek', h_hard:'hard drop', h_pause:'pauza', h_restart:'restart', h_menu:'menu', score:'WYNIK', lines:'LINIE', next:'NASTĘPNA', go1:'KONIEC GRY', go2:'Wciśnij R, aby zagrać ponownie', go3:'Wciśnij C, aby zobaczyć opisy', go4:'Naciśnij Esc, aby otworzyć menu', cleared:'LINIA!', double:'PODWÓJNA!', triple:'POTRÓJNA!' },
  de: { kicker:'WILLKOMMEN BEI', tagline:'Klassische Blockmechanik, neu erdacht. Wähle dein Theme, räume Zeilen und schau zu, wie sie explodieren — bevor die Blöcke die Decke erreichen.', pick:'— STIL WÄHLEN —', d_classic:'Arcade-Feeling der 80er — pur, einfach, retro', d_neon:'Neon, Chrom und die Nachstadt', d_rune:'Gold, Runen und magische Steine', d_space:'Sternenfelder, Gold und Stahl', lang:'SPRACHE', bg:'HINTERGRUND', st:'Statisch', an:'Animiert', play:'SPIELEN', k_space:'Leertaste', h_move:'bewegen', h_rot:'drehen', h_soft:'fallen lassen', h_hard:'Hard Drop', h_pause:'Pause', h_restart:'Neustart', h_menu:'Menü', score:'PUNKTE', lines:'ZEILEN', next:'NÄCHSTE', go1:'GAME OVER', go2:'Drücke R zum Neustart', go3:'Drücke C, um die Abspann zu sehen', go4:'Drücke Esc, um das Menü zu sehen', cleared:'GEKLÄRT!', double:'DOPPEL!', triple:'DOPPEL-DOPPEL!' },
  fr: { kicker:'BIENVENUE DANS', tagline:'La mécanique classique des blocs qui tombent, réinventée. Choisis ton thème, élimine les lignes et regarde-les exploser — avant que les briques n\u0027atteignent le plafond.', pick:'— CHOISIS UN STYLE —', d_classic:'L\u0027ambiance arcade des années 80 — pure, simple, rétro', d_neon:'N\u00e9on, chrome et ville de nuit', d_rune:'Or, runes et pierres enchant\u00e9es', d_space:'Champ d\u0027\u00e9toiles, or et acier', lang:'LANGUE', bg:'FOND', st:'Statique', an:'Anim\u00e9', play:'JOUER', k_space:'Espace', h_move:'d\u00e9placer', h_rot:'pivoter', h_soft:'descendre', h_hard:'chute directe', h_pause:'pause', h_restart:'recommencer', h_menu:'menu', score:'SCORE', lines:'LIGNES', next:'SUIVANT', go1:'PARTIE TERMIN\u00c9E', go2:'Appuyez sur R pour rejouer', go3:'Appuyez sur C pour voir les crédits', go4:'Appuyez sur Esc pour voir le menu', cleared:'\u00c9LIMIN\u00c9 !', double:'DOUBLE !', triple:'TRIPLE !' },
  es: { kicker:'BIENVENIDO A', tagline:'La mecánica clásica de bloques que caen, reimaginada. Elige tu tema, completa líneas y míralas explotar — antes de que los bloques toquen el techo.', pick:'— ELIGE UN ESTILO —', d_classic:'El ambiente arcade de los 80 — puro, simple, retro', d_neon:'Ne\u00f3n, cromo y ciudad nocturna', d_rune:'Oro, runas y piedras encantadas', d_space:'Campo estelar, oro y acero', lang:'IDIOMA', bg:'FONDO', st:'Est\u00e1tico', an:'Animado', play:'JUGAR', k_space:'Espacio', h_move:'mover', h_rot:'girar', h_soft:'bajar', h_hard:'ca\u00edda dura', h_pause:'pausa', h_restart:'reiniciar', h_menu:'men\u00fa', score:'PUNTOS', lines:'L\u00cdNEAS', next:'SIGUIENTE', go1:'FIN DE LA PARTIDA', go2:'Pulsa R para volver a jugar', go3:'Pulsa C para ver los créditos', go4:'Pulsa Esc para ver el menú', cleared:'\u00a1COMPLETADA!', double:'\u00a1DOBLE!', triple:'\u00a1TRIPLE!' },
  sv: { kicker:'W\u00c4LKOMMEN TILL', tagline:'Klassisk mekanik för fallande block, omtolkad. Välj ditt tema, rensa rader och titta på hur de exploderar — innan blocken når taket.', pick:'— V\u00c4LJ EN STIL —', d_classic:'80-talets arcade-känsla — ren, enkel, retro', d_neon:'Neon, krom och nattstad', d_rune:'Guld, runor och magiska stenar', d_space:'Stj\u00e4rnf\u00e4lt, guld och st\u00e4l', lang:'SPR\u00c5K', bg:'BAKGRUND', st:'Statisk', an:'Animerad', play:'SPELA', k_space:'Mellanslag', h_move:'flytta', h_rot:'rotera', h_soft:'f\u00e4lla', h_hard:'h\u00e5rdfall', h_pause:'paus', h_restart:'starta om', h_menu:'meny', score:'PO\u00c4NG', lines:'RADER', next:'N\u00c4STA', go1:'SPELET \u00c4R SLUT', go2:'Tryck R f\u00f6r att spela igen', go3:'Tryck C för att se texten', go4:'Tryck Esc för att se menyn', cleared:'RENSAD!', double:'DUBBEL!', triple:'TRIPEL!' },
  it: { kicker:'BENVENUTO IN', tagline:'La meccanica classica dei blocchi che cadono, ridisegnata. Scegli il tuo tema, completa le righe e guardale esplodere — prima che i blocchi tocchino il soffitto.', pick:'— SCEGLI UN STILE —', d_classic:'L\u0027atmosfera arcade degli anni 80 — pura, semplice, retro', d_neon:'Neon, cromo e citt\u00e0 notturna', d_rune:'Oro, rune e pietre incantate', d_space:'Campo stellare, oro e acciaio', lang:'LINGUAGGIO', bg:'SFONDO', st:'Statico', an:'Animato', play:'GIOCA', k_space:'Spazio', h_move:'muovi', h_rot:'ruota', h_soft:'fai scendere', h_hard:'drop duro', h_pause:'pausa', h_restart:'riavvia', h_menu:'menu', score:'PUNTI', lines:'RIGHE', next:'PROSSIMA', go1:'GAME OVER', go2:'Premi R per rigiocare', go3:'Premi C per i crediti', go4:'Premi Esc per vedere il menu', cleared:'COMPLETATA!', double:'DOPPIA!', triple:'TRIPLO!' },
  id: { kicker:'SELAMAT DATANG DI', tagline:'Mekanika blok jatuh klasik, dibalut baru. Pilih temamu, selesaikan baris dan saksikan semuanya meledak — sebelum blok-blok menabrak langit-langit.', pick:'— PILIH GAYA —', d_classic:'Suasana arcade era 80-an — murni, sederhana, retro', d_neon:'Neon, krom dan kota malam', d_rune:'Emas, rune dan batu sihir', d_space:'Lapangan bintang, emas dan baja', lang:'BAHASA', bg:'LATAR BELAKANG', st:'Statis', an:'Animasi', play:'MAIN', k_space:'Spasi', h_move:'gerak', h_rot:'putar', h_soft:'jatuh', h_hard:'drop keras', h_pause:'jeda', h_restart:'mulai ulang', h_menu:'menu', score:'SKOR', lines:'BARIS', next:'BERIKUTNYA', go1:'PERMAINAN SELESAI', go2:'Tekan R untuk main lagi', go3:'Tekan C untuk melihat kredit', go4:'Tekan Esc untuk melihat menu', cleared:'BERSIH!', double:'GANDA!', triple:'TRIPLE!' },
  cs: { kicker:'VÍTENÍ', tagline:'Klasická mechanika padajících kostek, znovu vymyšlená. Zvol si téma, odstraňuj řádky a buj v explozech — než kostky dosáhnou stropu.', pick:'— ZVOL STYL —', d_classic:'Klimat 80. let — prostý, retro arcade', d_neon:'Neon, chrom a noční město', d_rune:'Zlato, runy a zaklínácké kameny', d_space:'Poloha hvězd, zlato a ocel', lang:'JAZYK', bg:'POZADÍ', st:'Statický', an:'Animovaný', play:'HRÁT', k_space:'Mezerník', h_move:'pohyb', h_rot:'otočení', h_soft:'spuštění', h_hard:'tvrdé spuštění', h_pause:'pauza', h_restart:'restart', h_menu:'menu', score:'BODY', lines:'ŘÁDKY', next:'DALŠÍ', go1:'KONEC HRY', go2:'Stiskni R pro znovuhru', go3:'Stiskni C pro titulky', go4:'Stiskni Esc pro zobrazení menu', cleared:'ODSTRANĚNO!', double:'DVOJITá!', triple:'TROJITá!' },
  da: { kicker:'VELKOMMEN', tagline:'Klassisk blokmekanik, genopfundet. Vælg dit tema, ryd rækker og se dem eksplodere — før blokkene rammer loftet.', pick:'— VÆLG EN STIL —', d_classic:'Arcade-fornemmelsen fra 80\u0027erne — ren, simpel, retro', d_neon:'Neon, krom og natten by', d_rune:'Guld, rune og magiske sten', d_space:'Stjerner, guld og stål', lang:'SPROG', bg:'BAGGRUND', st:'Statisk', an:'Animeret', play:'SPIL', k_space:'Mellemrum', h_move:'BEVÆG', h_rot:'ROTÉR', h_soft:'SÆNKE', h_hard:'HÅRDT FALD', h_pause:'pause', h_restart:'genstart', h_menu:'menu', score:'POENG', lines:'RÆKKER', next:'KOMMENDE', go1:'GAME OVER', go2:'Tryk R for at spille igen', go3:'Tryk C for at se kreditterne', go4:'Tryk Esc for at se menuet', cleared:'RYDDET!', double:'DOBBELT!', triple:'TREDOBBELT!' },
  et: { kicker:'TÄHTNISTE', tagline:'Klassikaline langevate blokkide mehaanika, uuesti kujundatud. Vali oma teemat, eemalda ridad ja vaata, kuidas need plahvatavad — enne kui blokad kattni jõuavad.', pick:'— VALI STIIL —', d_classic:'80ndate arcade-tunne — puhas, lihtne, retro', d_neon:'Neoon, kroom ja öölinn', d_rune:'Kuld, runad ja loitsukivid', d_space:'Tähtede väli, kuld ja teras', lang:'KEEL', bg:'TAUST', st:'Staatiline', an:'Animeeritud', play:'MäNGIMA!', k_space:'VÄLI', h_move:'LIIGUTA', h_rot:'PÖÖRA', h_soft:'LASKE', h_hard:'KARU LÄSKEV', h_pause:'PAUS', h_restart:'ALOITA UUDESTEEN', h_menu:'VALIKU', score:'PUNKTID', lines:'RIDAD', next:'JÄÄRNEV', go1:'MÄÄNU LÄBI', go2:'NAHKA R, ET MÄÄNATA UUSNASTI', go3:'Vajuta C credits vaadat', go4:'Vajuta Esc menü nägemiseks', cleared:'PUHASTATUD!', double:'KAHS KORDA!', triple:'KOLM KORDA!' },
  fi: { kicker:'TERVETULOA', tagline:'Klassinen palikkamekaniikka uudelleen suunniteltu. Valitse teemasi, tyhjennä rivit ja katso niiden räjähtäminen — ennen kuin palikat osuvat kattoon.', pick:'— VALITSE TYYLI —', d_classic:'80-luvun arcade-tunnelma — puhdas, yksinkertainen, retro', d_neon:'Neon, kromi ja yökaupunki', d_rune:'Kulta, runat ja taian kivet', d_space:'Tähtikenttä, kulta ja teräs', lang:'KIELI', bg:'TAUSTA', st:'Staattinen', an:'Animoitu', play:'PELAA', k_space:'Välilyönti', h_move:'SIIRTO', h_rot:'KIERTä', h_soft:'LASKE', h_hard:'KOVA PUDOTUS', h_pause:'TAUKO', h_restart:'ALOITA UUDESTEEN', h_menu:'VALIKKO', score:'PISTEET', lines:'RIVIT', next:'SEURAAVA', go1:'PELI PÄÄTTYI', go2:'Paina R ja jatka uudestaan', go3:'Paina C nähdäksesi tekstit', go4:'Paina Esc nähdäksesi valikon', cleared:'PUHDISTETTU!', double:'KAKSOIN!', triple:'KOLME RIVIÄ!' },
  hr: { kicker:'DOBRO DOŠLO', tagline:'Klasična mehanika padajućih blokova u novom izdanju. Odaberi svoju temu, čisti redove i uživaj u eksplozijama — prije nego što blokovi udare u strop.', pick:'— ODABERI STIL —', d_classic:'Klimat 80-ih — čist, jednostavan, retro', d_neon:'Neon, krom i noćni grad', d_rune:'Zlato, rune i uročeni kamen', d_space:'Zvijezdana polja, zlato i čelik', lang:'JEZIK', bg:'POZADINA', st:'Statično', an:'Animirano', play:'IGRAJ', k_space:'RAZMAKNICA', h_move:'POKRET', h_rot:'OKRET', h_soft:'SPUST', h_hard:'TVRDO SPUST', h_pause:'PAUZA', h_restart:'PONOVNO', h_menu:'IZBORNIK', score:'BODOVI', lines:'RETKI', next:'SLJEDEĆI', go1:'KRAJ IGRE', go2:'Pritisni R za ponovnu igru', go3:'Pritisni C za napise', go4:'Pritisni Esc da vidiš izbornik', cleared:'POČIŠĆENO!', double:'DVOJNO!', triple:'TROJNO!' },
  hu: { kicker:'ÜDVÖZÖLÜ', tagline:'A klasszikus zuhanygó kockák mechanikája új formában. Válassz témát, törölj sorokat és élved a robbanásokait — mielőtt a blokkok elérnék a plafont.', pick:'— VÁLASZTÓD STÍLUST —', d_classic:'80-as évek arcade hangulata — tiszta, egyszerű, retro', d_neon:'Neon, króm és az éjszakai város', d_rune:'Arany, runák és bűvös kövek', d_space:'Csillagmező, arany és acél', lang:'NYELV', bg:'HÁTTÉR', st:'Statikus', an:'Animált', play:'JÁTÉK', k_space:'SZÓKÖZ', h_move:'MOZGATÁS', h_rot:'FORGATÁS', h_soft:'LELÖTÉS', h_hard:'KOVÁCS LÖTÉS', h_pause:'SZÜNET', h_restart:'ÚJRAINDÍTÁS', h_menu:'MENÜ', score:'PONTSZÁM', lines:'SOROK', next:'KÖVETKEZŐ', go1:'GAME OVER', go2:'Nyomd meg az R-t az újrajátszáshoz', go3:'Nyomsd meg a C-t a stáblistához', go4:'Nyomd meg az Esc-ot a menü megtekintéséhez', cleared:'LETÖRÖLTE!', double:'DUPLA!', triple:'HÁROM!' },
  lv: { kicker:'LAIPNA', tagline:'Klasiska krītošo bloku mehānika jaunā izskatā. Izvēlies savu tēmu, notīri rindas un skaties, kā tās sprāgst — pirms bloki sasniedz griestus.', pick:'— IZVĒLIES STILU —', d_classic:'80. gadu arcade noskaņa — tīra, vienkārša, retro', d_neon:'Neons, hroms un nakts pilsēta', d_rune:'Zelts, runas un vestures akmeņi', d_space:'Zvaigžņu lauks, zelts un tāls', lang:'VALODA', bg:'FONS', st:'Statisks', an:'Animēts', play:'SPĒLĒT', k_space:'Atstarpe', h_move:'kustēties', h_rot:'grozīt', h_soft:'laist', h_hard:'ciests kritiens', h_pause:'pauze', h_restart:'restarts', h_menu:'izvēlne', score:'PUNKTI', lines:'RINDAS', next:'NÁKAMÁIS', go1:'SPĒLE BEIGTA', go2:'Nospied R, lai spēlētu vēlreiz', go3:'Nospied C, lai redzētu titulus', go4:'Nospied Esc, lai redzētu izvēlni', cleared:'NOTĪRĪTS!', double:'DVĪNKÁRŠS!', triple:'TRĪSKÁRŠS!' },
  lt: { kicker:'SVEIKI ATĖJUS', tagline:'Klasikinė kritančių blokų mechanika naujame pavidale. Pasirink savo temą, valyk eilutes ir stebėk, kaip jos sprogsta — kol pastatai pasiek lubas.', pick:'— PASIRINK STILĮ —', d_classic:'80-ųjų arcade dvasia — gryna, paprasta, retro', d_neon:'Neonas, chromas ir nakties miestas', d_rune:'Auras, runos ir burtų akmenys', d_space:'Žvaigždės laukas, auksas ir plienas', lang:'Kalba', bg:'FONAS', st:'Statinis', an:'Animuotas', play:'ŽAISTI', k_space:'Tarpas', h_move:'judėjimas', h_rot:'sukimas', h_soft:'leisk kristi', h_hard:'staigus kritimas', h_pause:'pauzė', h_restart:'restartas', h_menu:'meniu', score:'TAŠKAI', lines:'EILUTĖS', next:'SEKANTIS', go1:'GAME OVER', go2:'Spausk R, žaidžiau dar kartą', go3:'Spausk C, kad pamatytum kreditus', go4:'Paspausk Esc, kad pamatytumėte meniu', cleared:'IŠVALYTA!', double:'DVIGUBAI!', triple:'TRISKART!' },
  no: { kicker:'VELKOMMEN', tagline:'Klassisk blokk-mekanikk, nytt drakt. Velg ditt tema, rydd rader og se dem eksplodere — før blokkene når taket.', pick:'— VELG EN STIL —', d_classic:'80-tallets arcade-fornemmelse — ren, enkel, retro', d_neon:'Neon, krom og nattbyen', d_rune:'Gull, runer og magiske steiner', d_space:'Stjernesky, gull og stål', lang:'SPRAK', bg:'BAKGRUNN', st:'Statisk', an:'Animert', play:'SPILE', k_space:'Mellomrom', h_move:'beveg', h_rot:'rotere', h_soft:'senk', h_hard:'hard landing', h_pause:'pause', h_restart:'start på nytt', h_menu:'meny', score:'POENG', lines:'RADER', next:'NESTE', go1:'GAME OVER', go2:'Trykk R for å spille igjen', go3:'Trykk C for å se tekstene', go4:'Trykk Esc for å se menyen', cleared:'RYDDET!', double:'DOBBEL!', triple:'TRIPPEL!' },
  pt: { kicker:'BEM-VINDO AO', tagline:'A mecânica classic dos blocos que caem, reimajinada. Escolhe o teu tema, limpa as linhas e vê-las explodir — antes que os blocos toquem no teto.', pick:'— ESCOLHE UM ESTILO —', d_classic:'O clima arcade dos anos 80 — puro, simples, retró', d_neon:'Neon, crómio e cidade noturna', d_rune:'Ouro, runas e pedras encantadas', d_space:'Campo de estrelas, ouro e aço', lang:'IDIOMA', bg:'FUNDO', st:'Estático', an:'Animado', play:'JOGAR', k_space:'Espaço', h_move:'mover', h_rot:'rodar', h_soft:'descer', h_hard:'queda dura', h_pause:'pausa', h_restart:'reiniciar', h_menu:'menu', score:'PONTOS', lines:'LINHAS', next:'SEGUINTE', go1:'FIM DE JOGO', go2:'Carrega R para jogar outra vez', go3:'Carrega C para ver os créditos', go4:'Prima Esc para ver o menu', cleared:'LIMPA!', double:'DOBRO!', triple:'TRIPLO!' },
  ro: { kicker:'BINE AI VENIT', tagline:'Mecanica classică a blocurilor care cad, reimaginată. Alege-ți tema, curăță liniile și privește-le cum explodă — înainte ca blocurile să atingă tavanul.', pick:'— ALEGE UN STIL —', d_classic:'Clima arcade din anii 80 — pură, simplă, retro', d_neon:'Neon, crom și orașul de noapte', d_rune:'Aur, rune și pietre încântate', d_space:'Câmp stelar, aur și otel', lang:'LIMBĂ', bg:'FUNDAL', st:'Static', an:'Animat', play:'JOACĂ', k_space:'Spațiu', h_move:'MIȘCARE', h_rot:'ROTIRE', h_soft:'SCADE', h_hard:'CADERE DURĂ', h_pause:'PAUZĂ', h_restart:'REPORNIRE', h_menu:'MENIU', score:'PUNCTE', lines:'LINII', next:'URMĂTOAREA', go1:'JOC TERMINAT', go2:'Apasă R pentru a juca din nou', go3:'Apasă C pentru a vedea creditul', go4:'Apasă Esc pentru a vedea meniul', cleared:'CURĂȚAT!', double:'DUBLĂ!', triple:'TRIPPLU!' },
  sk: { kicker:'VÍT AJ V', tagline:'Klasická mechanika padajúcich blokov, znova vymyslená. Zvol si tému, odstraňuj riadky a buj v explozích — predtým, než kostky dosiahnu strop.', pick:'— VYBER STYL —', d_classic:'Klimat 80. rokov — čestý, retro arcade', d_neon:'Neón, chróm a nočné mesto', d_rune:'Zlato, runy a zakliate kameny', d_space:'Hviezdne pole, zlato a oceľ', lang:'JAZYK', bg:'POZADIE', st:'Statický', an:'Animovaný', play:'HRAŤ', k_space:'Medzerník', h_move:'pohyb', h_rot:'rotácia', h_soft:'spustenie', h_hard:'tvrdé spustenie', h_pause:'pauza', h_restart:'reštart', h_menu:'menu', score:'BODY', lines:'RIADKY', next:'ĎAĽŠÍ', go1:'KONIEC HRY', go2:'Stlač R na znovuhru', go3:'Stlač C pre titulky', go4:'Stlač Esc na zobrazenie menu', cleared:'ODSTRÁRENÉ!', double:'DVOJITá!', triple:'TROJITá!' },
  sl: { kicker:'DOBRO DOŠLO', tagline:'Klasična mehanka padajočih blokov v novem izdanju. Izberi svojo temo, počisti vrstice in uživaj v eksplozijah — preden bloki dosežejo strop.', pick:'— IZBERI STILO —', d_classic:'Klimat 80ih — čist, preprost, retro', d_neon:'Neoni, hrom in nočno mesto', d_rune:'Zlato, rune in urokani kamen', d_space:'Zvezdno polje, zlato in jeklo', lang:'JAZIK', bg:'OZADJE', st:'Statično', an:'Animirano', play:'IGRAJ', k_space:'PRESLEDNICA', h_move:'POMIK', h_rot:'ROTACIJA', h_soft:'SPUST', h_hard:'TRDI SPUST', h_pause:'PAVZA', h_restart:'PONASTAVITEV', h_menu:'MENI', score:'TOČKE', lines:'VRSTICE', next:'NASLEDNJI', go1:'KONEC IGRE', go2:'Pritisni R za ponovno igro', go3:'Pritisni C za napisne', go4:'Pritisni Esc za prikaz menija', cleared:'POČIŠČENO!', double:'DVOJNO!', triple:'TROJNI!' },
  tr: { kicker:'HOŞ GELDİN', tagline:'Klasik düşen blok mekaniği yeniden yorumlandı. Temanı seç, satırları temizle ve patlamalarını izle — bloklar tavana ulaşmadan önce.', pick:'— BİR TARZ SEÇ —', d_classic:'80\u0027ler arcade havası — saf, basit, retro', d_neon:'Neon, krom ve gece kenti', d_rune:'Altın, runlar ve büyülü taşlar', d_space:'Yıldızlar, altın ve çelik', lang:'DİL', bg:'ARKAPLAN', st:'Durum', an:'Animasyonlu', play:'OYNA', k_space:'Boşluk', h_move:'hareket', h_rot:'DÖNDÜR', h_soft:'İNDİR', h_hard:'SERT DÜŞÜŞ', h_pause:'mola', h_restart:'yeniden başlat', h_menu:'menü', score:'SKOR', lines:'SATIR', next:'SONRAKI', go1:'OYUN BİTTİ', go2:'Yeniden oynamak için R tuşu', go3:'C tuşuna basarak credits izle', go4:'Menüyü görmek için Esc tuşuna bas', cleared:'TEMİZLENDİ!', double:'ÇİFT!', triple:'ÜÇLÜ!' },
  el: { kicker:'ΚΑΛΩΣ ΗΘΕΣ', tagline:'Η κλασική μηχανική των πτώσων, επαναφασμένο. Επίλεξε το θέμα σου, καθαρίζεις τις γραμμές και απολαύεις τις εκρήξεις — πριν τα κομμάτια φτάσουν στην οροφή.', pick:'— ΕΠΙΛΕΞΕ ΣΤΥΛ —', d_classic:'Ατμόσφαιρα arcade των \u002780 — καθαρή, απλή, ρετρό', d_neon:'Νεον, χρώμιο και νυχτερινή πόλη', d_rune:'Χρυσός, ρώγες και μαγεμένοι λίθοι', d_space:'Πολο των αστέρων, χρυσός και χάλυβας', lang:'ΓΛΩΣΣΑ', bg:'ΥΦΟΣ', st:'Στατική', an:'Κινούμενη', play:'ΠΑΙΞΟΜΑΙ', k_space:'Διαστήμα', h_move:'ΚΙΗΣΗ', h_rot:'ΣΤΡΟΦΗ', h_soft:'ΚΑΘΩΤΕΡΑ', h_hard:'ΣΚΛΗΡΗ ΠΤΩΣΗ', h_pause:'ΠΑΥΣΗ', h_restart:'ΕΠΑΝΕΚΚΙΝΗΣΗ', h_menu:'ΜΕΝΟΥ', score:'ΒΑΘΜΟΙ', lines:'ΓΡΑΜΜΕΣ', next:'ΕΠΟΜΕΝΟ', go1:'ΤΕΛΟΣ ΠΑΙΞΙΜΟΥ', go2:'Πάτησε R για να ξαναπαίξεις', go3:'Πάτησε C για τα credits', go4:'Πάτησε Esc για να δεις το μενού', cleared:'ΚΑΘΑΡΙΣΤΗΚΕ!', double:'ΔΙΠΛΗ!', triple:'ΤΡΙΠΛΗ!' },
  ru: { kicker:'ДОБРО ПОЖАЛОВАТЬ', tagline:'Классическая механика падающих блоков — в новом свете. Выбери свою тему, зачищай линии и наблюдай взрывы — прежде чем блоки достанут до потолка.', pick:'— ВЫБЕРИ СТИЛЬ —', d_classic:'Дух аркад 80-х — чистый, простой, ретро', d_neon:'Неон, хром и ночной город', d_rune:'Золото, руны и чарованные камни', d_space:'Поле звёзд, золото и сталь', lang:'ЯЗЫК', bg:'ФОН', st:'Статичный', an:'Анимированный', play:'ИГРАТЬ', k_space:'Пробел', h_move:'движение', h_rot:'поворот', h_soft:'спуск', h_hard:'жёсткий спуск', h_pause:'пауза', h_restart:'перезапуск', h_menu:'меню', score:'ОЧКИ', lines:'ЛИНИИ', next:'СЛЕДУЮЩИЙ', go1:'ИГРА ОКОНЧЕНА', go2:'Нажми R, чтобы начать заново', go3:'Нажми C, чтобы посмотреть титры', go4:'Нажмите Esc, чтобы открыть меню', cleared:'ЗАЧИЩЕНО!', double:'ДВОЙНАЯ!', triple:'ТРОЙНАЯ!' },
  uk: { kicker:'ЛАСКАВО ПРОСИМО', tagline:'Класична механіка падаючих блоків — у новому вигляді. Обери свою тему, прибирай рядки і спостерігай за вибухами — до того, як блоки досягнуть стелі.', pick:'— ОБЕРИ СТИЛЬ —', d_classic:'Дух аркад 80-х — чистий, простий, ретро', d_neon:'Неон, хром і нічне місто', d_rune:'Золото, руни та зачаровані камені', d_space:'Зоряне поле, золото і сталь', lang:'МОВА', bg:'ФОН', st:'Статичний', an:'Анімований', play:'ГРАТИ', k_space:'Пробіл', h_move:'рух', h_rot:'обертати', h_soft:'спуск', h_hard:'жорсткий спуск', h_pause:'пауза', h_restart:'перезапуск', h_menu:'меню', score:'РАХУНОК', lines:'РЯДКИ', next:'НАСТУПНИЙ', go1:'КІНЕЦЬ ГРИ', go2:'Натисни R, щоб грати знову', go3:'Натисни C, щоб побачити титри', go4:'Натисніть Esc, щоб відкрити меню', cleared:'ВИДАЛЕНО!', double:'ПОДВОЄНЕ!', triple:'ПОТРОЄНЕ!' },
  th: { kicker:'ยินดีต้อนรับสู่', tagline:'กลไกบล็อกตกแบบคลาสสิก ในชุดใหม่ เลือกจังหวะของคุณ ทำลายแถว และสนุกกับการระเบิด — ก่อนที่บล็อกจะถึงเพดาน', pick:'— เลือกสไตล์ —', d_classic:'บรรยากาศอาร์เคดยุค 80 — บริสุทธิ์ เรียบง่าย คลาสสิก', d_neon:'นีออน โครเมียม และเมืองยามค่ำคืน', d_rune:'ทองคำ รัน และหินเวทมนตร์', d_space:'ทุ่งดาว ทองคำ และเหล็กกล้า', lang:'ภาษา', bg:'พื้นหลัง', st:'นิ่ง', an:'เคลื่อนไหว', play:'เล่น', k_space:'สเปซบาร์', h_move:'เลื่อน', h_rot:'หมุน', h_soft:'ร่วงลง', h_hard:'ร่วงด่วน', h_pause:'พัก', h_restart:'เริ่มใหม่', h_menu:'เมนู', score:'คะแนน', lines:'แถว', next:'ถัดไป', go1:'จบเกม', go2:'กด R เพื่อเล่นอีกครั้ง', go3:'กด C เพื่อดูเครดิต', go4:'กด Esc เพื่อดูเมนู', cleared:'ล้างแล้ว!', double:'คู่!', triple:'สามแถว!' },
  zh: { kicker:'欢迎来到', tagline:'经典的方块掉落力学，重新演绎。选择你自己的主题，消除行，欣赏它们爆炸——在方块触及天花板之前。', pick:'— 选择风格 —', d_classic:'80年代的街机氛围——纯净、简单、复古', d_neon:'霓虹、铬、夜之城', d_rune:'黄金、符文、被魔化的石头', d_space:'星空、黄金与钢铁', lang:'语言', bg:'背景', st:'静态', an:'动画', play:'开始游戏', k_space:'空格', h_move:'移动', h_rot:'旋转', h_soft:'下降', h_hard:'硬降', h_pause:'暂停', h_restart:'重开', h_menu:'菜单', score:'分数', lines:'行数', next:'下一个', go1:'游戏结束', go2:'按 R 重新开始', go3:'按下 C 查看演职员表', go4:'按 Esc 查看菜单', cleared:'消行!', double:'双消!', triple:'三消!' },
  ja: { kicker:'ようこそ', tagline:'定番の落ちるブロックの仕組みが、新しい形で再登場。テーマを選んで、行を消し、爆発を眺めて — ブロックが天井に触れる前に。', pick:'— スタイルを選択 —', d_classic:'80年代アーケードの香り — 純粋、シンプル、レトロ', d_neon:'ネオン、クロム、夜の街', d_rune:'黄金、ルーン、魔法の石', d_space:'星空、黄金、そして鋼', lang:'言語', bg:'背景', st:'静止', an:'アニメーション', play:'プレイ', k_space:'スペース', h_move:'移動', h_rot:'回転', h_soft:'落下', h_hard:'ハードドロップ', h_pause:'一時停止', h_restart:'リセット', h_menu:'メニュー', score:'スコア', lines:'ライン', next:'次のブロック', go1:'ゲームオーバー', go2:'Rキーで再プレイ', go3:'Cキーでスタッフロールを表示', go4:'Escキーでメニューを表示', cleared:'消去!', double:'ダブル!', triple:'トリプル!' },
  ko: { kicker:'환영합니다', tagline:'클래식한 블록 낙하 메카니즘, 새로운 모습으로 재탄생. 주제의 테마를 고르고, 줄을 지우며, 폭발을 향유해 주세요 — 블록이 천장에 닿기 전에.', pick:'— 스타일 선택 —', d_classic:'80년대 아케이드의 분위기 — 순수하고 단순한, 레트로', d_neon:'네온, 크롬, 밤의 도시', d_rune:'황금, 룬, 마법 깃든 돌', d_space:'별밭, 황금, 강철', lang:'언어', bg:'배경', st:'정지', an:'애니메이션', play:'플레이', k_space:'스페이스바', h_move:'이동', h_rot:'회전', h_soft:'내리기', h_hard:'하드 드롭', h_pause:'일시정지', h_restart:'재시작', h_menu:'메뉴', score:'점수', lines:'라인', next:'다음', go1:'게임 오버', go2:'R 키로 다시 플레이', go3:'C 키를 눌러 크레딧을 확인하세요', go4:'Esc 키를 눌러 메뉴 보기', cleared:'지우기!', double:'더블!', triple:'트리플!' },
  vi: { kicker:'CHÀO MỪNG ĐẾN VỚI', tagline:'Cơ chế khối rơi klasik, tái hiện mới. Chọn chủ đề của bạn, xóa sạch các hàng và xem chúng nổ tung — trước khi các khối chạm trần.', pick:'— CHỌN PHÔNG CÁCH —', d_classic:'Hương vị arcade thập niên 80 — tinh khiết, đơn giản, retro', d_neon:'Neon, chrom và thành phố về đêm', d_rune:'Vàng, phù văn và đá ma thuật', d_space:'Trường sao, vàng và thép', lang:'NGÔN NGỮ', bg:'NỀN TẢNG', st:'Tĩnh', an:'Động', play:'CHƠI', k_space:'PHÍM CÁCH', h_move:'DI CHUYỂN', h_rot:'XOAY', h_soft:'RƠI MỀM', h_hard:'RƠI CỨNG', h_pause:'TẠM DỪNG', h_restart:'KHỞI LẠI', h_menu:'THỰC ĐƠN', score:'ĐIỂM', lines:'HÀNG', next:'TIẾP THEO', go1:'HẾT TRÒ CHƠI', go2:'Nhấn R để chơi lại', go3:'Nhấn C để xem credits', go4:'Nhấn Esc để xem menu', cleared:'DỌN HANG!', double:'HAI HANG!', triple:'BA HANG!' },
  nl: { kicker:'WELKOM BIJ', tagline:'De klassieke vallende-blokkenmechanica, in nieuw jasje. Kies je thema, ruim rijen vrij en zie ze ontploffen — voordat de blokken de top bereiken.', pick:'— KIES EEN STIJL —', d_classic:'Arcade-gevoel van de jaren 80 — puur, simpel, retro', d_neon:'Neon, chroom en de nachtstad', d_rune:'Goud, runen en betoverde stenen', d_space:'Sterrenvelden, goud en staal', lang:'TAAL', bg:'ACHTERGROND', st:'Statisch', an:'Geanimeerd', play:'SPELEN', k_space:'Spatie', h_move:'bewegen', h_rot:'draaien', h_soft:'laten vallen', h_hard:'hard neerzetten', h_pause:'pauze', h_restart:'herstarten', h_menu:'menu', score:'PUNTEN', lines:'RIJEN', next:'VOLGENDE', go1:'EINDE SPEL', go2:'Druk op R om opnieuw te spelen', go3:'Druk op C om de credits te zien', go4:'Druk op Esc om het menu te zien', cleared:'GERUIMD!', double:'DUBBEL!', triple:'TRIPLET!' },
  hi: { kicker:'आपका स्वागत है', tagline:'क्लासिक ब्लॉक-गिरावट मैकानिक्स, नए रूप में। अपना थीम चुनें, पंक्तियों को साफ़ करें और उन्हें ब्लॉक छूने से पहले बिखरते देखें।', pick:'— एक शैली चुनें —', d_classic:'80s आर्केड वाइब — शुद्ध, सरल, रिट्रो', d_neon:'नियॉन, क्रोम और रात का शहर', d_rune:'सोना, रूनेज और जादुई पत्थर', d_space:'तारों का मैदान, सोना और स्टील', lang:'भाषा', bg:'पृष्ठभूमि', st:'स्थिर', an:'एनिमेटेड', play:'खेलें', k_space:'स्पेस', h_move:'चलाएँ', h_rot:'घुमाएँ', h_soft:'गिराएँ', h_hard:'हार्ड ड्रॉप', h_pause:'रोकें', h_restart:'दोबारा शुरू करें', h_menu:'मेन्यू', score:'स्कोर', lines:'पंक्तियाँ', next:'अगला', go1:'गेम ओवर', go2:'फिर से खेलने के लिए R दबाएँ', go3:'क्रेडिट देखने के लिए C दबाएँ', go4:'मेनू देखने के लिए Esc दबाएँ', cleared:'साफ़!', double:'डबल!', triple:'ट्रिपल!' },
  bn: { kicker:'স্বাগতম', tagline:'ক্লাসিক ব্লক-ফল গেমপ্লে, নতুন চেহারা। আপনার থিম বেছে নিন, লাইনগুলো মুছে ফেলুন এবং ব্লক ছাদে পৌঁছানোর আগে সেগুলোর বিস্ফোরণ দেখুন।', pick:'— একটি স্টাইল বেছে নিন —', d_classic:'৮০-এর আর্কেড ভাইব — নির্মল, সরল, রিট্রো', d_neon:'নয়ন, ক্রোম এবং রাতের শহর', d_rune:'সোনা, রুন এবং জাদুকরী পাথর', d_space:'তারা-ক্ষেত্র, সোনা এবং ইস্পাত', lang:'ভাষা', bg:'পটভূমি', st:'স্থির', an:'অ্যানিমেটেড', play:'খেলা', k_space:'স্পেস', h_move:'হান', h_rot:'ঘোরান', h_soft:'ফেলুন', h_hard:'হার্ড ড্রপ', h_pause:'বিরতি', h_restart:'পুনরায় শুরু', h_menu:'মেনু', score:'স্কোর', lines:'লাইন', next:'পরবর্তী', go1:'গেম শেষ', go2:'আবার খেলতে R চেপে দিন', go3:'ক্রেডিট দেখতে C চেপে দিন', go4:'মেনু দেখতে Esc চেপে দিন', cleared:'মুছে গেছে!', double:'ডাবল!', triple:'ট্রিপল!' },
  ar: { kicker:'مرحباً بك', tagline:'آلية بلوكات السقوط الكلاسيكية بمظهر جديد. اختر ثيمتك، امسح الصفوف، وشاهدها تنفجر — قبل أن تصل الكتل إلى السقف.', pick:'— اختر أسلوبك —', d_classic:'أجواء أركيد الثمانينات — نقية، بسيطة، ريترو', d_neon:'نيون وكروم ومدينة الليل', d_rune:'ذهب وروانات وأحجار مسحورة', d_space:'حقول النجوم والذهب والفولاذ', lang:'اللغة', bg:'الخلفية', st:'ثابت', an:'متحرك', play:'العب', k_space:'المسافة', h_move:'تحريك', h_rot:'تدوير', h_soft:'إسقاط ناعم', h_hard:'إسقاط صلب', h_pause:'إيقاف مؤقت', h_restart:'إعادة', h_menu:'القائمة', score:'النقاط', lines:'الصفوف', next:'التالي', go1:'انتهت اللعبة', go2:'اضغط R للعب مرة أخرى', go3:'اضغط C لعرض الشكر', go4:'اضغط Esc لعرض القائمة', cleared:'تم!', double:'مزدوج!', triple:'ثلاثي!' },
  bg: { kicker:'Добре дошли в', tagline:'Класическата механика на падащите блокове, преизмислена. Избери тема си, чисти редове и гледай как експлодират — преди блоковете да стигнат до тавана.', pick:'— Избери стил —', d_classic:'Аркадна атмосфера от 80-те — чисто, пресно, ретро', d_neon:'Неон, хром и нощният град', d_rune:'Злато, руни и магически камъни', d_space:'Звездни полета, злато и стомана', lang:'ЕЗИК', bg:'ФОН', st:'Статичен', an:'Анимиран', play:'ИГРАЙ', k_space:'Интервал', h_move:'движение', h_rot:'ротация', h_soft:'мек спуск', h_hard:'твърд спуск', h_pause:'пауза', h_restart:'рес', h_menu:'меню', score:'РЕЗУЛТАТ', lines:'РЕДОВЕ', next:'СЛЕДВАЩ', go1:'КРАЙ НА ИГРАТА', go2:'Натисни R за нова игра', go3:'Натисни C за титрите', go4:'Натисни Esc за да видиш менюто', cleared:'ЧИСТО!', double:'ДВОЙНО!', triple:'ТРОЙНО!' },
  sr: { kicker:'Добро дошли у', tagline:'Класична механика падајућих блокова, преизмишљена. Изабери тему, чисти редове и гледај како експлодирају — пре него што блокови стигну до плафона.', pick:'— Изабери стил —', d_classic:'Аркадска атмосфера из осамдесетих — чисто, пресно, ретро', d_neon:'Неон, хром и ноћни град', d_rune:'Злато, руни и зачарани камен', d_space:'Звездана поља, злато и челик', lang:'ЈЕЗИК', bg:'ПОЗАДИНА', st:'Статично', an:'Анимирано', play:'ИГРАЈ', k_space:'Space', h_move:'померање', h_rot:'ротација', h_soft:'мек спуск', h_hard:'тврдо спускане', h_pause:'пауза', h_restart:'рес', h_menu:'менjу', score:'РЕЗУЛАТ', lines:'РЕДОВИ', next:'СЛЕДЕЋИ', go1:'КРАЈ ИГРЕ', go2:'Притисни R за нову игру', go3:'Притисни C за титуле', go4:'Притисни Esc да видиш мени', cleared:'ЧИСТО!', double:'ДУБЛ!', triple:'ТРИПЛ!' },
};
let lang = 'en'; // always start in English (per-session choice only)
const LANGUAGES = [
  { code: 'id', name: 'Bahasa Indonesia' },
  { code: 'cs', name: 'Cčeština' },
  { code: 'da', name: 'Dansk' },
  { code: 'de', name: 'Deutsch' },
  { code: 'et', name: 'Eesti' },
  { code: 'en', name: 'English' },
  { code: 'es', name: 'Español' },
  { code: 'fr', name: 'Français' },
  { code: 'hr', name: 'Hrvatski' },
  { code: 'it', name: 'Italiano' },
  { code: 'lv', name: 'Latviešu' },
  { code: 'lt', name: 'Lietuviū' },
  { code: 'hu', name: 'Magyar' },
  { code: 'nl', name: 'Nederlands' },
  { code: 'no', name: 'Norsk' },
  { code: 'pl', name: 'Polski' },
  { code: 'pt', name: 'Português' },
  { code: 'ro', name: 'Română' },
  { code: 'sk', name: 'Slovenčina' },
  { code: 'sl', name: 'Slovenščina' },
  { code: 'fi', name: 'Suomi' },
  { code: 'sv', name: 'Svenska' },
  { code: 'vi', name: 'Tiếng Việt' },
  { code: 'tr', name: 'Türkçe' },
  { code: 'el', name: 'Ελληνικά' },
  { code: 'ru', name: 'Русский' },
  { code: 'uk', name: 'Українська' },
  { code: 'th', name: 'พอร' },
  { code: 'zh', name: '中文' },
  { code: 'ja', name: '日本語' },
  { code: 'ko', name: '한국어' },
  { code: 'bg', name: 'Български' },
  { code: 'sr', name: 'Српски' },
  { code: 'ar', name: 'العربية' },
  { code: 'bn', name: 'অাংলা' },
  { code: 'hi', name: 'हिन्दी' },
];
const langBtn = document.getElementById('langBtn');
const langMenu = document.getElementById('langMenu');
const langdd = document.getElementById('langdd');
function renderLangMenu() {
  const cur = LANGUAGES.find(l => l.code === lang) || LANGUAGES[0];
  langBtn.textContent = cur.name + ' ▾';
  langMenu.innerHTML = '';
  // List shows the OTHER languages — the active one disappears from the list
  LANGUAGES.filter(l => l.code !== lang).forEach(l => {
    const b = document.createElement('button');
    b.className = 'langitem';
    b.type = 'button';
    b.textContent = l.name;
    b.addEventListener('click', () => {
      langdd.classList.remove('open');
      applyLang(l.code);
    });
    langMenu.appendChild(b);
  });
}
function applyLang(code) {
  if (!L10N[code]) return;
  lang = code;
  document.documentElement.lang = code;
  const RTL_LANGS = ['ar', 'he', 'fa', 'ur']; // RTL languages — mirror the UI
  document.documentElement.dir = RTL_LANGS.includes(code) ? 'rtl' : 'ltr';
  const d = L10N[code];
  document.querySelectorAll('[data-i18n]').forEach(el => { el.textContent = d[el.dataset.i18n]; });
  renderLangMenu();
}
langBtn.addEventListener('click', e => { e.stopPropagation(); langdd.classList.toggle('open'); });
document.addEventListener('click', e => { if (!langdd.contains(e.target)) langdd.classList.remove('open'); });
